name: CI Chat-Hotel

on:
  push:
    branches: ["main"] # Vérifie que ta branche s'appelle bien main
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm install

      - name: Vérification du Build (Vite)
        run: npm run build
